### ISSUE TITLE
Can't successfully deploy base-valid.yaml: MinimumReplicasUnavailable

### ISSUE THREAD

**Issue by hjoly2003** [amitsaha/kubernetes-static-checkers-demo#1]
Hi, when I try to deploy your **base-valid.yaml** file, I get a **MinimumReplicasUnavailable** status from the dashboard.

Here's the corresponding Pod information, as obtained from `kubectl describe pods http-echo`:

```yaml
Name:         http-echo-57dd74545-ztdjv
Namespace:    default
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Sat, 13 Nov 2021 09:50:50 -0500
Labels:       app=http-echo
              pod-template-hash=57dd74545
Annotations:  <none>
Status:       Running
IP:           172.17.0.5
IPs:
  IP:           172.17.0.5
Controlled By:  ReplicaSet/http-echo-57dd74545
Containers:
  http-echo:
    Container ID:  docker://0413c8283b14ef6e7afa06ffc944411be2b2975a1d80aaa99b2bf1bab61f6f95
    Image:         hashicorp/http-echo
    Image ID:      docker-pullable://hashicorp/http-echo@sha256:ba27d460cd1f22a1a4331bdf74f4fccbc025552357e8a3249c40ae216275de96
    Port:          5678/TCP
    Host Port:     0/TCP
    Args:
      -text
      hello-world
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sat, 13 Nov 2021 10:47:53 -0500
      Finished:     Sat, 13 Nov 2021 10:47:53 -0500
    Ready:          False
    Restart Count:  16
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vcj8l (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-vcj8l:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  59m                    default-scheduler  Successfully assigned default/http-echo-57dd74545-ztdjv to minikube
  Normal   Pulled     59m                    kubelet            Successfully pulled image "hashicorp/http-echo" in 2.506047126s
  Normal   Pulled     59m                    kubelet            Successfully pulled image "hashicorp/http-echo" in 734.275667ms
  Normal   Pulled     59m                    kubelet            Successfully pulled image "hashicorp/http-echo" in 873.489459ms
  Normal   Created    58m (x4 over 59m)      kubelet            Created container http-echo
  Normal   Pulled     58m                    kubelet            Successfully pulled image "hashicorp/http-echo" in 816.982125ms
  Normal   Started    58m (x4 over 59m)      kubelet            Started container http-echo
  Normal   Pulling    58m (x5 over 59m)      kubelet            Pulling image "hashicorp/http-echo"
  Normal   Pulled     58m                    kubelet            Successfully pulled image "hashicorp/http-echo" in 773.840667ms
  Warning  BackOff    4m33s (x252 over 59m)  kubelet            Back-off restarting failed container

```

I'm using minikube on a Mac M1.

Thanks in advance
